### ISSUE TITLE
contact-form.json 404 (Not Found)

### ISSUE THREAD

**Issue by mendokusan** [spences10/svelte-and-airtable-contact-form-example#11]
Hello, 
I ran into an issue while trying out the app, I was wondering if there was a reason behind it. I also tried to change it to the file name with the exact path and still got the same error? I wonder if it has something to do with the server.
This is the error that is displayed on console log:
**POST http://localhost:3000/contact-form.json 404 (Not Found)**

And this is the location of the code that tried to fetch the js file:
```
  const res = await fetch('/contact-form.json', {
      method: 'POST',
      body: formData,
    })
```
I was hoping if there would be a solution for this issue. Any advice would be appreciated as well.

**Comment by spences10** [comment]
Hey @mendokusan, when you 'trying out the app' do you mean the [example]?

That's deployed to Vercel, the project uses the `@sveltejs/adapter-auto` dependency for that.

So I just tried the example and seems to work fine, so I'm guessing this is your instance of it, right?

Have you set up the environment keys for it?

Check out the [blog post] for a bit more detail on getting set up.

Thanks


[example]: https://svelte-and-airtable-contact-form-example.vercel.app//
[blog post]: https://scottspence.com/posts/make-a-contact-form-with-sveltekit-and-airtable
